### ISSUE TITLE
Shell task Extract fails to save

### ISSUE THREAD

**Issue by smarek** [ADmad/cakephp-i18n#36]
I'm not sure what messages and in what format should be present in sources, for Shell ExtractTask to work as intended.

This is with empty DB, config I18n.languages [en,de,fr]

No difference to the error was made by using different configuration of task (core messages y/n, merge into default domain y/n, change sources to only something simple such as app/src/Template/Email)

```
Exception: SQLSTATE[HY000]: General error: 1364 Field 'value_0' doesn't have a default value in [/var/www/app/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php, line 39]
2019-02-28 07:46:05 Error: [PDOException] SQLSTATE[HY000]: General error: 1364 Field 'value_0' doesn't have a default value in /var/www/app/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php on line 39
Stack Trace:
#0 /var/www/app/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php(39): PDOStatement->execute(NULL)
#1 /var/www/app/vendor/cakephp/cakephp/src/Database/Connection.php(334): Cake\Database\Statement\MysqlStatement->execute()
#2 /var/www/app/vendor/cakephp/cakephp/src/Core/Retry/CommandRetry.php(68): Cake\Database\Connection->Cake\Database\{closure}()
#3 /var/www/app/vendor/cakephp/cakephp/src/Database/Connection.php(337): Cake\Core\Retry\CommandRetry->run(Object(Closure))
#4 /var/www/app/vendor/cakephp/cakephp/src/Database/Query.php(219): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 /var/www/app/vendor/cakephp/cakephp/src/ORM/Table.php(2114): Cake\Database\Query->execute()
#6 /var/www/app/vendor/cakephp/cakephp/src/ORM/Table.php(2008): Cake\ORM\Table->_insert(Object(Cake\ORM\Entity), Array)
#7 /var/www/app/vendor/cakephp/cakephp/src/ORM/Table.php(1921): Cake\ORM\Table->_processSave(Object(Cake\ORM\Entity), Object(ArrayObject))
#8 /var/www/app/vendor/cakephp/cakephp/src/ORM/Table.php(1634): Cake\ORM\Table->Cake\ORM\{closure}()
#9 /var/www/app/vendor/cakephp/cakephp/src/Database/Connection.php(738): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#10 /var/www/app/vendor/cakephp/cakephp/src/ORM/Table.php(1635): Cake\Database\Connection->transactional(Object(Closure))
#11 /var/www/app/vendor/cakephp/cakephp/src/ORM/Table.php(1922): Cake\ORM\Table->_executeTransaction(Object(Closure), true)
#12 /var/www/app/vendor/admad/cakephp-i18n/src/Shell/Task/ExtractTask.php(255): Cake\ORM\Table->save(Object(Cake\ORM\Entity))
#13 /var/www/app/vendor/admad/cakephp-i18n/src/Shell/Task/ExtractTask.php(214): ADmad\I18n\Shell\Task\ExtractTask->_save('default', 'You don't have ...', NULL, NULL, 'Controller/AppC...')
#14 /var/www/app/vendor/admad/cakephp-i18n/src/Shell/Task/ExtractTask.php(164): ADmad\I18n\Shell\Task\ExtractTask->_write()
#15 /var/www/app/vendor/admad/cakephp-i18n/src/Shell/Task/ExtractTask.php(88): ADmad\I18n\Shell\Task\ExtractTask->_extract()
#16 /var/www/app/vendor/admad/cakephp-i18n/src/Shell/I18nShell.php(38): ADmad\I18n\Shell\Task\ExtractTask->main()
#17 /var/www/app/vendor/cakephp/cakephp/src/Console/Shell.php(532): ADmad\I18n\Shell\I18nShell->main()
#18 /var/www/app/vendor/cakephp/cakephp/src/Console/CommandRunner.php(371): Cake\Console\Shell->runCommand(Array, true)
#19 /var/www/app/vendor/cakephp/cakephp/src/Console/CommandRunner.php(166): Cake\Console\CommandRunner->runShell(Object(ADmad\I18n\Shell\I18nShell), Array)
#20 /var/www/app/bin/cake.php(12): Cake\Console\CommandRunner->run(Array)
#21 {main}
```

**Comment by ADmad** [comment]
SQL for creating table updated in 87ee45d.
