### ISSUE TITLE
Argument 2 passed to Cake\I18n\TranslatorRegistry::setFallbackPackage()

### ISSUE THREAD

**Issue by amr-dallin** [ADmad/cakephp-i18n#62]
Hello.

Updated cakephp from 4.1.6 to 4.3.8 using [cakephp/upgrade](https://github.com/cakephp/upgrade).

Also updated [ADmad/cakephp-i18n](https://github.com/ADmad/cakephp-i18n) to 2.2.0.

Added code to config/bootstrap.php

```
I18n::config('cake', function ($domain, $locale) {
    return new \ADmad\I18n\I18n\DbMessagesLoader($domain, $locale);
});

I18n::config('default', function ($domain, $locale) {
    return new \ADmad\I18n\I18n\DbMessagesLoader($domain, $locale);
});

I18n::config('panel', function ($domain, $locale) {
    return new \ADmad\I18n\I18n\DbMessagesLoader($domain, $locale);
});

I18n::config('frontend', function ($domain, $locale) {
    return new \ADmad\I18n\I18n\DbMessagesLoader($domain, $locale);
});

I18n::config('frontend2', function ($domain, $locale) {
    return new \ADmad\I18n\I18n\DbMessagesLoader($domain, $locale);
});
```

Now I am getting this error:

```
Fatal error: [TypeError] Argument 2 passed to Cake\I18n\TranslatorRegistry::setFallbackPackage() must be an instance of Cake\I18n\Package, instance of ADmad\I18n\I18n\DbMessagesLoader given, called in /var/www/html/vendor/cakephp/cakephp/src/I18n/TranslatorRegistry.php on line 237 (/var/www/html/vendor/cakephp/cakephp/src/I18n/TranslatorRegistry.php:314) #0 /var/www/html/vendor/cakephp/cakephp/src/I18n/TranslatorRegistry.php(237): Cake\I18n\TranslatorRegistry->setFallbackPackage('default', Object(ADmad\I18n\I18n\DbMessagesLoader)) #1 /var/www/html/vendor/cakephp/cakephp/src/I18n/TranslatorRegistry.php(210): Cake\I18n\TranslatorRegistry->_getTranslator('default', 'en') #2 /var/www/html/vendor/cakephp/cakephp/src/I18n/I18n.php(148): Cake\I18n\TranslatorRegistry->get('default') #3 /var/www/html/vendor/cakephp/cakephp/src/I18n/functions.php(45): Cake\I18n\I18n::getTranslator() #4 /var/www/html/src/View/AppView.php(79): __('Bucheon Univers...') #5 /var/www/html/vendor/cakephp/cakephp/src/View/View.php(350): App\View\AppView->i in /var/www/html/vendor/cakephp/cakephp/src/Error/ErrorHandler.php on line 196

Fatal error: [TypeError] Argument 2 passed to Cake\I18n\TranslatorRegistry::setFallbackPackage() must be an instance of Cake\I18n\Package, instance of ADmad\I18n\I18n\DbMessagesLoader given, called in /var/www/html/vendor/cakephp/cakephp/src/I18n/TranslatorRegistry.php on line 237 (/var/www/html/vendor/cakephp/cakephp/src/I18n/TranslatorRegistry.php:314) #0 /var/www/html/vendor/cakephp/cakephp/src/I18n/TranslatorRegistry.php(237): Cake\I18n\TranslatorRegistry->setFallbackPackage('default', Object(ADmad\I18n\I18n\DbMessagesLoader)) #1 /var/www/html/vendor/cakephp/cakephp/src/I18n/TranslatorRegistry.php(210): Cake\I18n\TranslatorRegistry->_getTranslator('default', 'en') #2 /var/www/html/vendor/cakephp/cakephp/src/I18n/I18n.php(148): Cake\I18n\TranslatorRegistry->get('default') #3 /var/www/html/vendor/cakephp/cakephp/src/I18n/functions.php(45): Cake\I18n\I18n::getTranslator() #4 /var/www/html/src/View/AppView.php(79): __('Bucheon Univers...') #5 /var/www/html/vendor/cakephp/cakephp/src/View/View.php(350): App\View\AppView->i in /var/www/html/vendor/cakephp/cakephp/src/Error/ErrorHandler.php on line 196
```

Please advise a solution to the problem.

Thank you.

**Comment by ADmad** [comment]
Update your I18n::config() call as per the example shown in the readme https://github.com/ADmad/cakephp-i18n#dbmessagesloader.

**Comment by amr-dallin** [comment]
Thank you!
